name: Sahil Nishal
description: Portfolio
introduction: I'm a final year MCA student at Department of Computer Science, University of Delhi. I'm passionate about web and software development. If you're interested in knowing about my technical experience, checkout my Projects.

#social links
github: https://github.com/snishal
facebook: https://www.facebook.com/snishal/
linkedin: https://www.linkedin.com/in/sahil-nishal-20aa147b/
mail: sahil.mca18.du@gmail.com
phone: +91-9467918415